Direction\Domain\Entity\TouristSpotPrices:
    type: entity
    table: tourist_spot_prices
    indexes:
        fk_tourist_spot:
            columns:
                - tourist_spot_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        slug:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        titlePtBr:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: title_pt_br
        tripCost:
            type: string
            nullable: true
            length: 0
            options:
                fixed: false
            column: trip_cost
        default:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
    manyToOne:
        touristSpot:
            targetEntity: Direction\Domain\Entity\TouristSpots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tourist_spot_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
