Direction\Domain\Entity\Exchange:
    type: entity
    table: exchange
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: float
            nullable: false
            precision: 10
            scale: 8
        fromCurrency:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: from_currency
        toCurrency:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: to_currency
        createAt:
            type: datetime
            nullable: false
            column: create_at
        dateDue:
            type: datetime
            nullable: false
            column: date_due
    lifecycleCallbacks: {  }
