Direction\Domain\Entity\Currency:
    type: entity
    table: currency
    uniqueConstraints:
        code_UNIQUE:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
        symbol:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
