Direction\Domain\Entity\TouristSpots:
    type: entity
    table: tourist_spots
    indexes:
        fk_city_tourist_spots:
            columns:
                - city_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        touristSpotName:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: tourist_spot_name
        address:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        site:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        rate:
            type: decimal
            nullable: false
            precision: 2
            scale: 1
        visitationTimeFast:
            type: time
            nullable: true
            column: visitation_time_fast
        visitationTimeMedium:
            type: time
            nullable: true
            column: visitation_time_medium
        visitationTimeSlow:
            type: time
            nullable: true
            column: visitation_time_slow
        latitude:
            type: string
            nullable: true
            length: 155
            options:
                fixed: false
        longitude:
            type: string
            nullable: true
            length: 155
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        city:
            targetEntity: Direction\Domain\Entity\City
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                city_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
