Direction\Domain\Entity\DirectionRoutes:
    type: entity
    table: direction_routes
    indexes:
        fk_tourist_spots_routes_tourist_spots1_idx:
            columns:
                - tourist_spot_id_destination
        fk_tourist_spots_routes_tourist_spots:
            columns:
                - tourist_spot_id_origin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        distance:
            type: integer
            nullable: true
            options:
                unsigned: false
        duration:
            type: integer
            nullable: true
            options:
                unsigned: false
        routerType:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
                default: WALKING
            column: router_type
        departureTime:
            type: time
            nullable: true
            column: departure_time
        weekday:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        airportIdOrigin:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: airport_id_origin
        airportIdDestination:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: airport_id_destination
        placeIdOrigin:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: place_id_origin
        placeIdDestination:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: place_id_destination
        directionType:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: direction_type
    manyToOne:
        touristSpotOrigin:
            targetEntity: Direction\Domain\Entity\TouristSpots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tourist_spot_id_origin:
                    referencedColumnName: id
            orphanRemoval: false
        touristSpotDestination:
            targetEntity: Direction\Domain\Entity\TouristSpots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tourist_spot_id_destination:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
