Direction\Domain\Entity\TouristSpotImage:
    type: entity
    table: tourist_spot_image
    indexes:
        fk_tourist_spot_id_tourist_spot_image_idx:
            columns:
                - tourist_spot_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cover:
            type: boolean
            nullable: false
            options:
                default: '0'
    manyToOne:
        touristSpot:
            targetEntity: Direction\Domain\Entity\TouristSpots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tourist_spot_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
