Direction\Domain\Entity\CountryI18n:
    type: entity
    table: country_i18n
    indexes:
        country_fk:
            columns:
                - country_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        language:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        country:
            targetEntity: Direction\Domain\Entity\Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
