Direction\Domain\Entity\StateI18n:
    type: entity
    table: state_i18n
    indexes:
        state_fk:
            columns:
                - state_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        language:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        state:
            targetEntity: Direction\Domain\Entity\State
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
