Direction\Domain\Entity\TouristSpotsTime:
    type: entity
    table: tourist_spots_time
    indexes:
        fk_tourist_spot_id_tourist_spots_time:
            columns:
                - tourist_spot_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        periodStart:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: period_start
        periodEnd:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: period_end
        openingTime:
            type: time
            nullable: true
            column: opening_time
        closingTime:
            type: time
            nullable: true
            column: closing_time
        specialTime:
            type: boolean
            nullable: false
            column: special_time
        open:
            type: boolean
            nullable: false
        dayOfWeek:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: day_of_week
    manyToOne:
        touristSpot:
            targetEntity: Direction\Domain\Entity\TouristSpots
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tourist_spot_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
