Direction\Domain\Entity\DirectionGoogleApiKey:
    type: entity
    table: direction_google_api_key
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        apiKey:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: api_key
        applicationType:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: application_type
        email:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
